# Generated by Django 5.2.17 on 2026-09-08 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_sessiontoken'),
        ('inventory', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='accounts.client'),
        ),
        migrations.AddField(
            model_name='product',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.client'),
        ),
    ]
